function AboutPage() {
  return (
    <div className="text-center p-10">
      <h1 className="text-2xl font-bold my-2">About</h1>
      <p className="text-gray-300">Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quidem, placeat minus atque voluptas quaerat, assumenda, nulla voluptatibus maiores sit facere qui odio! Obcaecati quis nobis nemo in numquam cupiditate eveniet error eaque, veritatis quod doloremque ea dolorem ipsa totam adipisci. Unde sit, voluptates eius distinctio cum similique ad rem voluptate facilis consequuntur, dolor impedit neque ipsa. Aliquam distinctio deleniti officiis ad voluptate magnam earum voluptatum dicta vitae, sint quod quis soluta, at voluptatem corrupti dignissimos itaque? Iure voluptatem officia, laudantium minima vero aliquam quia. Quibusdam facere nisi reiciendis iusto placeat asperiores, eius molestias. Ipsum nesciunt velit, error obcaecati ratione atque adipisci eaque pariatur rem assumenda expedita unde deserunt quidem ullam inventore consequuntur esse iste fuga alias debitis. Labore illum facilis fugiat velit sequi exercitationem. Non cum laboriosam dolor exercitationem numquam soluta nostrum? Alias, quidem provident excepturi molestias eligendi voluptatem maiores numquam perspiciatis ab temporibus. Soluta aspernatur vero obcaecati ea non, ducimus numquam incidunt vitae quae ut veritatis provident saepe perspiciatis facilis eum tenetur voluptates repudiandae, nam, culpa placeat cum nulla inventore quisquam? Officiis perspiciatis alias at possimus? Dolores iure, obcaecati necessitatibus ipsam odio numquam possimus facilis provident dignissimos deserunt doloremque tempora nam quas voluptas? Mollitia, rem fugiat. At quisquam nemo eligendi velit explicabo eos quas minima aliquam veritatis sequi dolor suscipit odio provident nam repellat itaque placeat, quaerat laboriosam eveniet corporis ea. Alias reprehenderit temporibus maiores, odio asperiores molestiae magni beatae deleniti quod ab minima cum debitis totam odit a! Ipsa dolorum similique, saepe voluptate quis officia quidem aut facilis vero? Magnam doloribus recusandae, odio veritatis et ratione inventore eaque deserunt earum consectetur minus fuga voluptatem maiores cum repellendus consequuntur aperiam, harum animi. Facilis veniam ratione voluptatibus dicta velit placeat ipsam a. Tenetur, id atque consequatur ipsum distinctio debitis, eveniet pariatur magni, esse dicta explicabo sed reiciendis tempora maiores.</p>
    </div>
  );
}

export default AboutPage;
